// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "microapps-20181212001428-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://microapps-20181212001428-hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:bdc79f4d-56f7-40af-b6c0-7c6452cbca54",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_zjiMNF5Oy",
    "aws_user_pools_web_client_id": "4v500t3pqu56vmrl416q9eqll3",
    "aws_appsync_graphqlEndpoint": "https://kb32xz27xraozjp6gjjo7pid5i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
